#!/bin/bash
set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
IFS=$'\n\t'

HELP () {
  echo " "
  echo "Usage: sudo ddimage [name_of_the_image] [path_to_the_usb_drive] [fast|slow]"
  echo "Example: sudo ddimage debian.iso /dev/sdc slow"
  printf "\nDisplay Images:\n"
  ls -1v *.iso *.img 2>/dev/null
  printf "\nDisplay Drives:\n"
  #lsblk -pdn -o NAME
  ls -1 /dev/sd?
}

# Ensure we are root
if [[ $EUID -ne 0 ]]; then
  echo "ddimage must be run as root" 1>&2
  HELP
  exit 1
else
  # check if number of parameter equals 3 and only allow 'Images' and 'ISOs'
  # and only allow to write to drives which do not belong to the system!!
  # change (sda|sdb) to the drive names of your system.. (sda|nvme0|sde) or (sda) as an example..
  if [[ $# -eq 3 && $1 =~ (\.img|\.iso)$ && ! $2 =~ (sda|sdb) ]]
  then
    case $3 in
      slow)
        bs=4M
        oflag=sync
        ;;
      fast)
        bs=16M
        oflag=direct
        ;;
      *)
        echo "Invalid option: $3"
        HELP
        exit 1
        ;;
    esac
    printf "dd if=$1 of=$2 bs=$bs status=progress oflag=$oflag \n"
    read -p "Accept? [Y/n]: " yn
    [ "$yn" = "n" ] && exit
    dd if=$1 of=$2 bs=$bs status=progress oflag=$oflag
  else
    HELP
  fi
fi
